version: '3.8'
services:
  db:
    image: postgres:12-alpine
    container_name: db_app3
    environment:
        POSTGRES_PASSWORD: postgres
    expose:
      - 5432



    restart: always

  app:
    build: ./
    env_file:
      - .env-non-dev
    container_name: fastapi_3
    ports:
      - 7773:8000
    depends_on:
      - db
    restart: always